// Generates admin-app/migrations/0002_seed_catalog.sql from the live
// assets/js/products.js. The seed populates categories + products + their
// child rows (images, sizes, occasions, badges) so Phase 1b can verify the
// catalog round-trip end-to-end. Re-run after editing products.js.
//
// We sandbox-eval products.js because it's a browser-targeted script that
// expects a `window` global. Faking `window` in a vm context lets us read
// the catalog without depending on or polluting any other module.

import fs from "node:fs/promises";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const PRODUCTS_JS = path.join(REPO_ROOT, "assets", "js", "products.js");
const OUT_SQL = path.resolve(__dirname, "..", "migrations", "0002_seed_catalog.sql");

// Read products.js and run it in a sandbox where `window` is a plain object.
// After the script runs, our globals are siting on sandbox.window.
const source = await fs.readFile(PRODUCTS_JS, "utf8");
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(source, sandbox);

const categories = sandbox.window.KLINE_CATEGORIES;
const products = sandbox.window.KLINE_PRODUCTS;

if (!Array.isArray(categories) || !Array.isArray(products)) {
  throw new Error("products.js did not expose KLINE_CATEGORIES and KLINE_PRODUCTS arrays");
}

// SQL string-escape: wraps in single quotes and doubles internal single quotes.
const sqlString = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const sqlNullable = (s) => (s == null || s === "" ? "NULL" : sqlString(s));
const sqlInt = (n) => (n == null ? "NULL" : String(parseInt(n, 10)));

// SQL output is one big array of lines we join at the end. Easier than
// streaming and lets us add a header summary once we know the counts.
const lines = [];
const push = (line) => lines.push(line);

push("-- K-LINE MEN admin — seed catalog (Phase 1b)");
push("--");
push("-- Generated by admin-app/scripts/build-seed.mjs from assets/js/products.js.");
push("-- Do not edit by hand. Re-run `npm run db:seed:build` after editing products.js");
push("-- to regenerate this file, then re-apply migrations to refresh the catalog.");
push("--");
push(`-- Source rows: ${categories.length} categories, ${products.length} products.`);
push("--");
push("-- All seeded rows are status='published' so the live site sees them as");
push("-- already-approved content. Manager + Editor flows kick in for any future");
push("-- edits via the admin UI.");
push("");

// Categories. Insert with explicit sort_order matching the array order so the
// Shop page's category dropdown stays in the same order as products.js.
push(`-- Categories (${categories.length})`);
categories.forEach((cat, i) => {
  push(
    "INSERT INTO categories (slug, label, sort_order, status, created_by, updated_by) " +
      `VALUES (${sqlString(cat.slug)}, ${sqlString(cat.label)}, ${i}, 'published', 'seed', 'seed');`
  );
});
push("");

// Products. The category FK is resolved by slug at insert time so we don't
// have to predict autoincrement IDs. Each product also fans out into image,
// size, occasion, and badge child rows.
push(`-- Products (${products.length}) + child rows`);
let imageCount = 0;
let sizeCount = 0;
let occasionCount = 0;
let badgeCount = 0;

for (const p of products) {
  const categorySubquery = `(SELECT id FROM categories WHERE slug = ${sqlString(p.category)})`;
  push("");
  push(`-- ${p.id}: ${p.name}`);
  push(
    "INSERT INTO products (id, name, category_id, price, color_name, color_hex, description, status, created_by, updated_by) " +
      `VALUES (${sqlString(p.id)}, ${sqlString(p.name)}, ${categorySubquery}, ${sqlInt(p.price)}, ` +
      `${sqlNullable(p.color?.name)}, ${sqlNullable(p.color?.hex)}, ${sqlNullable(p.description)}, ` +
      `'published', 'seed', 'seed');`
  );

  // Images: primary first, then any gallery entries.
  const allImages = [p.image, ...(Array.isArray(p.gallery) ? p.gallery : [])].filter(Boolean);
  allImages.forEach((url, idx) => {
    push(
      "INSERT INTO product_images (product_id, url, sort_order) " +
        `VALUES (${sqlString(p.id)}, ${sqlString(url)}, ${idx});`
    );
    imageCount += 1;
  });

  // Sizes: stock_count left NULL — public site treats NULL as 'show by default'.
  if (Array.isArray(p.sizes)) {
    p.sizes.forEach((size, idx) => {
      push(
        "INSERT INTO product_sizes (product_id, size, sort_order) " +
          `VALUES (${sqlString(p.id)}, ${sqlString(size)}, ${idx});`
      );
      sizeCount += 1;
    });
  }

  if (Array.isArray(p.occasion)) {
    p.occasion.forEach((occ, idx) => {
      push(
        "INSERT INTO product_occasions (product_id, occasion, sort_order) " +
          `VALUES (${sqlString(p.id)}, ${sqlString(occ)}, ${idx});`
      );
      occasionCount += 1;
    });
  }

  if (Array.isArray(p.badges)) {
    p.badges.forEach((badge, idx) => {
      push(
        "INSERT INTO product_badges (product_id, badge, sort_order) " +
          `VALUES (${sqlString(p.id)}, ${sqlString(badge)}, ${idx});`
      );
      badgeCount += 1;
    });
  }
}

push("");
push("-- Settings singleton: pulls the contact/social constants out of the");
push("-- window.KLINE helper at the bottom of products.js so the dashboard");
push("-- doesn't start empty. Phase 1g's Site copy admin lets the owner edit.");
const k = sandbox.window.KLINE ?? {};
push(
  "INSERT INTO settings (id, whatsapp_display, whatsapp_raw, call_display, call_raw, email, instagram_handle, instagram_url) " +
    `VALUES (1, ${sqlNullable(k.WHATSAPP_DISPLAY)}, ${sqlNullable(k.WHATSAPP_RAW)}, ` +
    `${sqlNullable(k.CALL_DISPLAY)}, ${sqlNullable(k.CALL_RAW)}, ${sqlNullable(k.EMAIL)}, ` +
    `${sqlNullable(k.INSTAGRAM_HANDLE)}, ${sqlNullable(k.INSTAGRAM_URL)});`
);

push("");
push("-- Homepage and delivery_returns singletons start empty; Phase 1f / 1g fills them.");
push("INSERT INTO homepage (id) VALUES (1);");
push("INSERT INTO delivery_returns (id) VALUES (1);");
push("");

const summary =
  `-- Summary: ${categories.length} categories, ${products.length} products, ` +
  `${imageCount} images, ${sizeCount} sizes, ${occasionCount} occasions, ${badgeCount} badges, ` +
  "1 settings row, 1 homepage row, 1 delivery_returns row.";
push(summary);

await fs.mkdir(path.dirname(OUT_SQL), { recursive: true });
await fs.writeFile(OUT_SQL, lines.join("\n") + "\n", "utf8");

console.log(`✓ Wrote ${path.relative(REPO_ROOT, OUT_SQL)}`);
console.log(summary.replace(/^-- /, "  "));
