/* ============================================================================
   K-LINE MEN — Font fetcher
   Downloads Cormorant Garamond + Manrope (woff2, latin subset) from Google
   Fonts and writes a self-hosted assets/fonts/fonts.css with @font-face
   declarations pointing at the local files. Eliminates the runtime DNS lookup
   to fonts.googleapis.com and the cross-origin font request to gstatic.com,
   letting the browser start parsing the font files as soon as styles.css is
   discovered. Latin-only subset (English-language site) keeps total weight
   minimal.
   Run: npm run fetch:fonts
   ============================================================================ */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONTS_DIR = path.join(ROOT, 'assets', 'fonts');
const OUT_CSS = path.join(FONTS_DIR, 'fonts.css');

const FONTS_URL = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap';

// Modern Chrome UA — needed so Google Fonts returns woff2 (the most compact
// format). An ancient UA would get the woff/eot fallbacks we don't want.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function main() {
  await fs.mkdir(FONTS_DIR, { recursive: true });

  console.log('Fetching Google Fonts CSS…');
  const cssRes = await fetch(FONTS_URL, { headers: { 'User-Agent': UA } });
  if (!cssRes.ok) throw new Error('Failed to fetch CSS: ' + cssRes.status);
  const css = await cssRes.text();

  // Google Fonts groups @font-face declarations by subset, each preceded by a
  // /* subset */ comment. Walk pairs of (subset → block) and keep only latin.
  const blocks = [];
  const re = /\/\*\s*([a-z\-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let match;
  while ((match = re.exec(css)) !== null) {
    blocks.push({ subset: match[1], block: match[2] });
  }
  const latinBlocks = blocks.filter(b => b.subset === 'latin');
  console.log('Found ' + blocks.length + ' total @font-face blocks; keeping ' + latinBlocks.length + ' latin-subset.');
  if (latinBlocks.length === 0) {
    console.error('No latin-subset blocks found — Google Fonts may have changed format. Aborting.');
    process.exit(1);
  }

  let outputCss =
    '/* ============================================================================\n' +
    '   K-LINE MEN — self-hosted fonts (latin subset)\n' +
    '   AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand. To rotate\n' +
    '   weights or pick up upstream font updates, re-run `npm run fetch:fonts`.\n' +
    '   ============================================================================ */\n\n';

  let totalBytes = 0;
  for (const { block } of latinBlocks) {
    const familyMatch = block.match(/font-family:\s*'([^']+)'/);
    const weightMatch = block.match(/font-weight:\s*(\d+)/);
    const srcMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!familyMatch || !weightMatch || !srcMatch) continue;

    const family = familyMatch[1];
    const weight = weightMatch[1];
    const url = srcMatch[1];
    const filename = family.toLowerCase().replace(/\s+/g, '-') + '-' + weight + '.woff2';
    const localPath = path.join(FONTS_DIR, filename);

    const fontRes = await fetch(url);
    if (!fontRes.ok) throw new Error('Failed to fetch ' + url + ': ' + fontRes.status);
    const buffer = Buffer.from(await fontRes.arrayBuffer());
    await fs.writeFile(localPath, buffer);
    totalBytes += buffer.length;
    console.log('  ✓ ' + filename + ' (' + (buffer.length / 1024).toFixed(1) + ' KB)');

    // Rewrite the @font-face block: replace remote URL with a local relative
    // path resolved against the location of fonts.css itself.
    const rewritten = block.replace(/url\(https:\/\/[^)]+\)/, "url('" + filename + "')");
    outputCss += rewritten + '\n\n';
  }

  await fs.writeFile(OUT_CSS, outputCss);
  console.log('\n✓ ' + path.relative(ROOT, OUT_CSS) + '  (' + latinBlocks.length + ' faces, ' + (totalBytes / 1024).toFixed(1) + ' KB total)');
}

main().catch(err => { console.error(err); process.exit(1); });
